package com.ledger.app.ui.screens

import android.content.Intent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.navigation.NavController
import com.ledger.app.ui.components.LedgerCard
import com.ledger.app.ui.theme.*
import com.ledger.app.ui.util.buildCustomCsv
import com.ledger.app.ui.util.shareCsv
import com.ledger.app.ui.viewmodel.CategoryViewModel
import com.ledger.app.ui.viewmodel.TransactionViewModel
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.YearMonth
import java.time.format.DateTimeFormatter

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CustomReportScreen(
    navController: NavController,
    categoryViewModel: CategoryViewModel = hiltViewModel(),
    txViewModel: TransactionViewModel = hiltViewModel()
) {
    val catState by categoryViewModel.state.collectAsStateWithLifecycle()
    val txState  by txViewModel.state.collectAsStateWithLifecycle()
    val context  = LocalContext.current

    LaunchedEffect(Unit) { txViewModel.loadAll(1000u) }

    val now = LocalDate.now()
    val ymFmt = DateTimeFormatter.ofPattern("MMM yyyy")

    var startYm by remember { mutableStateOf(YearMonth.of(now.year, 1)) }
    var endYm   by remember { mutableStateOf(YearMonth.now()) }

    var showStartDatePicker by remember { mutableStateOf(false) }
    var showEndDatePicker   by remember { mutableStateOf(false) }

    val allCategoryNames = remember(catState.categories) { catState.categories.map { it.name } }
    val selectedCategories = remember(allCategoryNames) { mutableStateListOf(*allCategoryNames.toTypedArray()) }

    var includeExpenses by remember { mutableStateOf(true) }
    var includeIncome   by remember { mutableStateOf(true) }
    var selectedGrouping by remember { mutableStateOf("By Month") }
    val groupings = listOf("By Month", "By Category", "By Week", "By Day")

    var reportGenerated by remember { mutableStateOf(false) }

    // Computed report data (derived from state when report is generated)
    data class ReportSummary(
        val income: Double, val expenses: Double, val txCount: Int,
        val byMonth: List<Pair<String, Double>>,   // label → net
        val byCategory: List<Pair<String, Double>>,// category → total expense
        val byWeek: List<Pair<String, Double>>,    // week label → total
        val byDay: List<Pair<String, Double>>      // date → total
    )

    val reportData: ReportSummary? = remember(txState.transactions, startYm, endYm, selectedCategories.toList(), includeExpenses, includeIncome, reportGenerated) {
        if (!reportGenerated) return@remember null
        val filtered = txState.transactions.filter { tx ->
            val inRange = runCatching {
                val d = LocalDate.parse(tx.createdAt.take(10))
                val ym = YearMonth.of(d.year, d.monthValue)
                ym >= startYm && ym <= endYm
            }.getOrElse { false }
            val inCategory = selectedCategories.contains(tx.category)
            val inType = (includeIncome && tx.isIncome) || (includeExpenses && !tx.isIncome)
            inRange && inCategory && inType
        }

        val income   = filtered.filter { it.isIncome }.sumOf { it.amount }
        val expenses = filtered.filter { !it.isIncome }.sumOf { it.amount }

        val byMonth = filtered
            .groupBy { it.createdAt.take(7) } // "yyyy-MM"
            .mapValues { (_, txs) -> txs.sumOf { if (it.isIncome) it.amount else -it.amount } }
            .entries.sortedBy { it.key }
            .map { (key, net) ->
                val (yr, mo) = key.split("-").map { it.toInt() }
                val label = YearMonth.of(yr, mo).format(ymFmt)
                Pair(label, net)
            }

        val byCategory = filtered.filter { !it.isIncome }
            .groupBy { it.category }
            .mapValues { (_, txs) -> txs.sumOf { it.amount } }
            .entries.sortedByDescending { it.value }
            .map { Pair(it.key, it.value) }

        val byWeek = filtered
            .groupBy {
                val d = runCatching { LocalDate.parse(it.createdAt.take(10)) }.getOrNull() ?: return@groupBy "?"
                val weekStart = d.with(DayOfWeek.MONDAY)
                weekStart.toString()
            }
            .mapValues { (_, txs) -> txs.sumOf { if (it.isIncome) it.amount else -it.amount } }
            .entries.sortedBy { it.key }
            .map { (key, net) ->
                val d = runCatching { LocalDate.parse(key) }.getOrNull()
                val label = d?.format(DateTimeFormatter.ofPattern("MMM d")) ?: key
                Pair("Week of $label", net)
            }

        val byDay = filtered
            .groupBy { it.createdAt.take(10) }
            .mapValues { (_, txs) -> txs.sumOf { if (it.isIncome) it.amount else -it.amount } }
            .entries.sortedByDescending { it.value }
            .take(15)
            .map { (key, net) ->
                val d = runCatching { LocalDate.parse(key) }.getOrNull()
                val label = d?.format(DateTimeFormatter.ofPattern("MMM d, yyyy")) ?: key
                Pair(label, net)
            }

        ReportSummary(income, expenses, filtered.size, byMonth, byCategory, byWeek, byDay)
    }

    if (showStartDatePicker) {
        val state = rememberDatePickerState(initialSelectedDateMillis = startYm.atDay(1).toEpochDay() * 86_400_000L)
        DatePickerDialog(
            onDismissRequest = { showStartDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    state.selectedDateMillis?.let {
                        val d = LocalDate.ofEpochDay(it / 86_400_000L)
                        startYm = YearMonth.of(d.year, d.monthValue)
                        if (startYm > endYm) endYm = startYm
                    }
                    showStartDatePicker = false
                }) { Text("OK", color = Primary) }
            },
            dismissButton = { TextButton(onClick = { showStartDatePicker = false }) { Text("Cancel") } }
        ) { DatePicker(state = state) }
    }

    if (showEndDatePicker) {
        val state = rememberDatePickerState(initialSelectedDateMillis = endYm.atDay(1).toEpochDay() * 86_400_000L)
        DatePickerDialog(
            onDismissRequest = { showEndDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    state.selectedDateMillis?.let {
                        val d = LocalDate.ofEpochDay(it / 86_400_000L)
                        endYm = YearMonth.of(d.year, d.monthValue)
                        if (endYm < startYm) startYm = endYm
                    }
                    showEndDatePicker = false
                }) { Text("OK", color = Primary) }
            },
            dismissButton = { TextButton(onClick = { showEndDatePicker = false }) { Text("Cancel") } }
        ) { DatePicker(state = state) }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Custom Report", style = MaterialTheme.typography.headlineSmall) },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    if (txState.isLoading || catState.isLoading) {
                        Box(modifier = Modifier.padding(end = 12.dp), contentAlignment = Alignment.Center) {
                            CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp, color = Primary)
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = SurfaceContainerLow)
            )
        },
        containerColor = SurfaceContainerLow
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp, vertical = 24.dp),
            verticalArrangement = Arrangement.spacedBy(20.dp)
        ) {
            // Date range
            Text("Date Range", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        OutlinedButton(
                            onClick = { showStartDatePicker = true },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Icon(Icons.Filled.CalendarMonth, contentDescription = null, tint = Primary, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("From: ${startYm.format(ymFmt)}", color = OnSurface, style = MaterialTheme.typography.bodySmall)
                        }
                        OutlinedButton(
                            onClick = { showEndDatePicker = true },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Icon(Icons.Filled.CalendarMonth, contentDescription = null, tint = Primary, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("To: ${endYm.format(ymFmt)}", color = OnSurface, style = MaterialTheme.typography.bodySmall)
                        }
                    }
                    Text("Quick select", style = MaterialTheme.typography.labelSmall, color = OnSurfaceVariant)
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        listOf("This Month", "Last 3M", "This Year", "Last Year").forEach { preset ->
                            AssistChip(
                                onClick = {
                                    val cur = YearMonth.now()
                                    when (preset) {
                                        "This Month" -> { startYm = cur;                              endYm = cur }
                                        "Last 3M"    -> { startYm = cur.minusMonths(2);               endYm = cur }
                                        "This Year"  -> { startYm = YearMonth.of(now.year, 1);        endYm = cur }
                                        "Last Year"  -> { startYm = YearMonth.of(now.year - 1, 1);    endYm = YearMonth.of(now.year - 1, 12) }
                                    }
                                    reportGenerated = false
                                },
                                label = { Text(preset, style = MaterialTheme.typography.labelSmall) }
                            )
                        }
                    }
                }
            }

            // Transaction type
            Text("Transaction Type", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(checked = includeExpenses, onCheckedChange = { includeExpenses = it; reportGenerated = false }, colors = CheckboxDefaults.colors(checkedColor = Tertiary))
                        Spacer(Modifier.width(8.dp))
                        Text("Expenses", style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(checked = includeIncome, onCheckedChange = { includeIncome = it; reportGenerated = false }, colors = CheckboxDefaults.colors(checkedColor = Primary))
                        Spacer(Modifier.width(8.dp))
                        Text("Income", style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                    }
                }
            }

            // Categories
            Text("Categories", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(2.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("${selectedCategories.size}/${allCategoryNames.size} selected", style = MaterialTheme.typography.labelMedium, color = OnSurfaceVariant)
                        TextButton(onClick = {
                            if (selectedCategories.size == allCategoryNames.size) {
                                selectedCategories.clear()
                            } else {
                                selectedCategories.clear()
                                selectedCategories.addAll(allCategoryNames)
                            }
                            reportGenerated = false
                        }) {
                            Text(
                                if (selectedCategories.size == allCategoryNames.size) "Deselect All" else "Select All",
                                color = Primary, style = MaterialTheme.typography.labelMedium
                            )
                        }
                    }
                    if (allCategoryNames.isEmpty()) {
                        Text("No categories found.", style = MaterialTheme.typography.bodySmall, color = OnSurfaceVariant)
                    } else {
                        allCategoryNames.forEach { cat ->
                            Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                                Checkbox(
                                    checked = selectedCategories.contains(cat),
                                    onCheckedChange = { checked ->
                                        if (checked) selectedCategories.add(cat) else selectedCategories.remove(cat)
                                        reportGenerated = false
                                    },
                                    colors = CheckboxDefaults.colors(checkedColor = Primary)
                                )
                                Spacer(Modifier.width(8.dp))
                                Text(cat, style = MaterialTheme.typography.bodyMedium, color = OnSurface)
                            }
                        }
                    }
                }
            }

            // Grouping
            Text("Group By", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    groupings.forEach { g ->
                        Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                            RadioButton(
                                selected = selectedGrouping == g,
                                onClick = { selectedGrouping = g; reportGenerated = false },
                                colors = RadioButtonDefaults.colors(selectedColor = Primary)
                            )
                            Spacer(Modifier.width(8.dp))
                            Text(g, style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                        }
                    }
                }
            }

            Spacer(Modifier.height(4.dp))
            if (txState.isLoading || catState.isLoading) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.Center,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    CircularProgressIndicator(modifier = Modifier.size(24.dp), strokeWidth = 2.5.dp, color = Primary)
                    Spacer(Modifier.width(12.dp))
                    Text("Loading data…", style = MaterialTheme.typography.bodyMedium, color = OnSurfaceVariant)
                }
            } else {
                Button(
                    onClick = { reportGenerated = true },
                    modifier = Modifier.fillMaxWidth().height(52.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = Primary),
                    shape = RoundedCornerShape(6.dp),
                    enabled = selectedCategories.isNotEmpty() && (includeExpenses || includeIncome)
                ) {
                    Icon(Icons.Filled.Assessment, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(Modifier.width(8.dp))
                    Text("Generate Report", style = MaterialTheme.typography.labelLarge)
                }
            }

            // Inline report results
            reportData?.let { report ->
                val net = report.income - report.expenses
                HorizontalDivider(color = OutlineVariant.copy(alpha = 0.3f))
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        "${startYm.format(ymFmt)} – ${endYm.format(ymFmt)}",
                        style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold
                    )
                    // Export button — built from the filtered transactions stored in reportData
                    val filteredTxs = remember(txState.transactions, startYm, endYm, selectedCategories.toList(), includeExpenses, includeIncome) {
                        txState.transactions.filter { tx ->
                            val inRange = runCatching {
                                val d = LocalDate.parse(tx.createdAt.take(10))
                                val ym = YearMonth.of(d.year, d.monthValue)
                                ym >= startYm && ym <= endYm
                            }.getOrElse { false }
                            val inCategory = selectedCategories.contains(tx.category)
                            val inType = (includeIncome && tx.isIncome) || (includeExpenses && !tx.isIncome)
                            inRange && inCategory && inType
                        }
                    }
                    IconButton(onClick = {
                        val csv = buildCustomCsv(startYm, endYm, filteredTxs, selectedGrouping)
                        val fileName = "custom_report_${startYm.year}${"%02d".format(startYm.monthValue)}_${endYm.year}${"%02d".format(endYm.monthValue)}.csv"
                        context.startActivity(Intent.createChooser(shareCsv(context, fileName, csv), "Export CSV"))
                    }) {
                        Icon(Icons.Filled.Download, contentDescription = "Export CSV", tint = Primary)
                    }
                }

                // Summary
                LedgerCard(modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            Column(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(2.dp)) {
                                Text("INCOME", style = MaterialTheme.typography.labelSmall, color = OnSurfaceVariant)
                                Text("+${"$%,.2f".format(report.income)}", style = MaterialTheme.typography.titleMedium, color = Primary, fontWeight = FontWeight.Bold)
                            }
                            Column(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(2.dp)) {
                                Text("EXPENSES", style = MaterialTheme.typography.labelSmall, color = OnSurfaceVariant)
                                Text("-${"$%,.2f".format(report.expenses)}", style = MaterialTheme.typography.titleMedium, color = Tertiary, fontWeight = FontWeight.Bold)
                            }
                            Column(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(2.dp)) {
                                Text("NET", style = MaterialTheme.typography.labelSmall, color = OnSurfaceVariant)
                                Text(
                                    "${if (net >= 0) "+" else ""}${"$%,.2f".format(net)}",
                                    style = MaterialTheme.typography.titleMedium,
                                    color = if (net >= 0) Primary else Tertiary, fontWeight = FontWeight.Bold
                                )
                            }
                        }
                        Text("${report.txCount} transactions", style = MaterialTheme.typography.bodySmall, color = OnSurfaceVariant)
                    }
                }

                // Breakdown by selected grouping
                val breakdownRows: List<Pair<String, Double>> = when (selectedGrouping) {
                    "By Month"    -> report.byMonth
                    "By Category" -> report.byCategory
                    "By Week"     -> report.byWeek
                    "By Day"      -> report.byDay
                    else          -> report.byMonth
                }

                if (breakdownRows.isNotEmpty()) {
                    LedgerCard(modifier = Modifier.fillMaxWidth()) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Text(selectedGrouping, style = MaterialTheme.typography.titleSmall, color = OnSurfaceVariant, fontWeight = FontWeight.SemiBold)
                            breakdownRows.forEachIndexed { idx, (label, value) ->
                                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                    Text(label, style = MaterialTheme.typography.bodyMedium, color = OnSurface, modifier = Modifier.weight(1f))
                                    Text(
                                        if (selectedGrouping == "By Category")
                                            "${"$%,.2f".format(value)}"
                                        else
                                            "${if (value >= 0) "+" else ""}${"$%,.2f".format(value)}",
                                        style = MaterialTheme.typography.bodyMedium,
                                        color = if (selectedGrouping == "By Category") Tertiary
                                                else if (value >= 0) Primary else Tertiary,
                                        fontWeight = FontWeight.SemiBold
                                    )
                                }
                                if (idx < breakdownRows.lastIndex)
                                    HorizontalDivider(color = OutlineVariant.copy(alpha = 0.10f))
                            }
                        }
                    }
                } else {
                    LedgerCard(modifier = Modifier.fillMaxWidth()) {
                        Box(modifier = Modifier.fillMaxWidth().padding(24.dp), contentAlignment = Alignment.Center) {
                            Text("No transactions match the selected filters.", style = MaterialTheme.typography.bodyMedium, color = OnSurfaceVariant)
                        }
                    }
                }
            }
        }
    }
}
