package com.ledger.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.ledger.app.ui.components.LedgerCard
import com.ledger.app.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CustomReportScreen(navController: NavController) {
    // Date range
    var showStartDatePicker by remember { mutableStateOf(false) }
    var showEndDatePicker by remember { mutableStateOf(false) }
    var startDate by remember { mutableStateOf("Jan 2026") }
    var endDate by remember { mutableStateOf("Apr 2026") }

    // Categories
    val allCategories = listOf("Housing", "Food & Dining", "Transportation", "Entertainment", "Health", "Shopping", "Salary", "Freelance", "Investments")
    val selectedCategories = remember { mutableStateListOf(*allCategories.toTypedArray()) }

    // Type filter
    var includeExpenses by remember { mutableStateOf(true) }
    var includeIncome by remember { mutableStateOf(true) }

    // Format
    var selectedFormat by remember { mutableStateOf("PDF") }
    val formats = listOf("PDF", "CSV", "Excel")

    // Grouping
    var selectedGrouping by remember { mutableStateOf("By Month") }
    val groupings = listOf("By Month", "By Category", "By Week", "By Day")

    var reportGenerated by remember { mutableStateOf(false) }

    fun formatDate(millis: Long): String {
        val cal = java.util.Calendar.getInstance()
        cal.timeInMillis = millis
        val months = arrayOf("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
        return "${months[cal.get(java.util.Calendar.MONTH)]} ${cal.get(java.util.Calendar.YEAR)}"
    }

    if (showStartDatePicker) {
        val state = rememberDatePickerState()
        DatePickerDialog(
            onDismissRequest = { showStartDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    state.selectedDateMillis?.let { startDate = formatDate(it) }
                    showStartDatePicker = false
                }) { Text("OK", color = Primary) }
            },
            dismissButton = { TextButton(onClick = { showStartDatePicker = false }) { Text("Cancel") } }
        ) { DatePicker(state = state) }
    }

    if (showEndDatePicker) {
        val state = rememberDatePickerState()
        DatePickerDialog(
            onDismissRequest = { showEndDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    state.selectedDateMillis?.let { endDate = formatDate(it) }
                    showEndDatePicker = false
                }) { Text("OK", color = Primary) }
            },
            dismissButton = { TextButton(onClick = { showEndDatePicker = false }) { Text("Cancel") } }
        ) { DatePicker(state = state) }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Custom Report", style = MaterialTheme.typography.headlineSmall) },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = SurfaceContainerLow)
            )
        },
        containerColor = SurfaceContainerLow
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp, vertical = 24.dp),
            verticalArrangement = Arrangement.spacedBy(20.dp)
        ) {
            // Date range
            Text("Date Range", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        OutlinedButton(
                            onClick = { showStartDatePicker = true },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Icon(Icons.Filled.CalendarMonth, contentDescription = null, tint = Primary, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("From: $startDate", color = OnSurface, style = MaterialTheme.typography.bodySmall)
                        }
                        OutlinedButton(
                            onClick = { showEndDatePicker = true },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Icon(Icons.Filled.CalendarMonth, contentDescription = null, tint = Primary, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("To: $endDate", color = OnSurface, style = MaterialTheme.typography.bodySmall)
                        }
                    }

                    // Quick presets
                    Text("Quick select", style = MaterialTheme.typography.labelSmall, color = OnSurfaceVariant)
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        listOf("This Month", "Last 3M", "This Year", "Last Year").forEach { preset ->
                            AssistChip(
                                onClick = {
                                    when (preset) {
                                        "This Month" -> { startDate = "Apr 2026"; endDate = "Apr 2026" }
                                        "Last 3M"    -> { startDate = "Jan 2026"; endDate = "Apr 2026" }
                                        "This Year"  -> { startDate = "Jan 2026"; endDate = "Apr 2026" }
                                        "Last Year"  -> { startDate = "Jan 2025"; endDate = "Dec 2025" }
                                    }
                                },
                                label = { Text(preset, style = MaterialTheme.typography.labelSmall) }
                            )
                        }
                    }
                }
            }

            // Transaction type
            Text("Transaction Type", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(
                            checked = includeExpenses,
                            onCheckedChange = { includeExpenses = it },
                            colors = CheckboxDefaults.colors(checkedColor = Tertiary)
                        )
                        Spacer(Modifier.width(8.dp))
                        Text("Expenses", style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(
                            checked = includeIncome,
                            onCheckedChange = { includeIncome = it },
                            colors = CheckboxDefaults.colors(checkedColor = Primary)
                        )
                        Spacer(Modifier.width(8.dp))
                        Text("Income", style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                    }
                }
            }

            // Categories
            Text("Categories", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(2.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            "${selectedCategories.size}/${allCategories.size} selected",
                            style = MaterialTheme.typography.labelMedium,
                            color = OnSurfaceVariant
                        )
                        TextButton(onClick = {
                            if (selectedCategories.size == allCategories.size) {
                                selectedCategories.clear()
                            } else {
                                selectedCategories.clear()
                                selectedCategories.addAll(allCategories)
                            }
                        }) {
                            Text(
                                if (selectedCategories.size == allCategories.size) "Deselect All" else "Select All",
                                color = Primary,
                                style = MaterialTheme.typography.labelMedium
                            )
                        }
                    }
                    allCategories.forEach { cat ->
                        Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                            Checkbox(
                                checked = selectedCategories.contains(cat),
                                onCheckedChange = { checked ->
                                    if (checked) selectedCategories.add(cat) else selectedCategories.remove(cat)
                                },
                                colors = CheckboxDefaults.colors(checkedColor = Primary)
                            )
                            Spacer(Modifier.width(8.dp))
                            Text(cat, style = MaterialTheme.typography.bodyMedium, color = OnSurface)
                        }
                    }
                }
            }

            // Grouping
            Text("Group By", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            LedgerCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    groupings.forEach { g ->
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            RadioButton(
                                selected = selectedGrouping == g,
                                onClick = { selectedGrouping = g },
                                colors = RadioButtonDefaults.colors(selectedColor = Primary)
                            )
                            Spacer(Modifier.width(8.dp))
                            Text(g, style = MaterialTheme.typography.bodyLarge, color = OnSurface)
                        }
                    }
                }
            }

            // Format
            Text("Export Format", style = MaterialTheme.typography.titleMedium, color = OnSurface, fontWeight = FontWeight.SemiBold)
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                formats.forEach { fmt ->
                    FilterChip(
                        selected = selectedFormat == fmt,
                        onClick = { selectedFormat = fmt },
                        label = { Text(fmt) },
                        modifier = Modifier.weight(1f),
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = Primary,
                            selectedLabelColor = OnPrimary
                        ),
                        leadingIcon = if (selectedFormat == fmt) {
                            { Icon(Icons.Filled.Check, contentDescription = null, modifier = Modifier.size(16.dp)) }
                        } else null
                    )
                }
            }

            // Generated report card
            if (reportGenerated) {
                LedgerCard(modifier = Modifier.fillMaxWidth()) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Icon(Icons.Filled.CheckCircle, contentDescription = null, tint = Primary, modifier = Modifier.size(28.dp))
                        Column(modifier = Modifier.weight(1f)) {
                            Text("Report Ready", style = MaterialTheme.typography.titleMedium, color = OnSurface)
                            Text("$startDate – $endDate · $selectedFormat", style = MaterialTheme.typography.bodySmall, color = OnSurfaceVariant)
                        }
                        IconButton(onClick = { /* download */ }) {
                            Icon(Icons.Filled.Download, contentDescription = "Download", tint = Primary)
                        }
                    }
                }
            }

            Spacer(Modifier.height(8.dp))
            Button(
                onClick = { reportGenerated = true },
                modifier = Modifier.fillMaxWidth().height(52.dp),
                colors = ButtonDefaults.buttonColors(containerColor = Primary),
                shape = RoundedCornerShape(6.dp),
                enabled = selectedCategories.isNotEmpty() && (includeExpenses || includeIncome)
            ) {
                Icon(Icons.Filled.Assessment, contentDescription = null, modifier = Modifier.size(18.dp))
                Spacer(Modifier.width(8.dp))
                Text("Generate Report", style = MaterialTheme.typography.labelLarge)
            }
        }
    }
}
