[target.aarch64-linux-android]
linker = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"
ar = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"


[target.x86_64-linux-android]
linker = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android26-clang.cmd"
ar = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

[env]
CC_aarch64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

CC_x86_64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android26-clang.cmd"
CXX_aarch64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang++.cmd"

CXX_x86_64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android26-clang++.cmd"
AR_aarch64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

AR_x86_64_linux_android = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
ANDROID_NDK_HOME = "C:/Users/dedek/AppData/Local/Android/Sdk/ndk/30.0.14904198"
